# Generated by Django 5.0.4 on 2024-05-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорию", "verbose_name_plural": "Категории"},
        ),
    ]
