# Generated by Django 5.0.4 on 2024-05-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(default=1, verbose_name="номер версии"),
                ),
                (
                    "version_name",
                    models.CharField(
                        default=None, max_length=100, verbose_name="название версии"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="текущая версия"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версию",
                "verbose_name_plural": "Версии",
            },
        ),
    ]
