# Generated by Django 5.0.4 on 2024-05-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.FloatField(default=1, verbose_name="номер версии"),
        ),
    ]
