# Generated by Django 4.2 on 2024-06-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name", "category", "price", "description"),
                "permissions": [
                    ("set_published_status", " can publish product"),
                    ("change_description", "can change product description"),
                    ("change_category", " can change product category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
