# Generated by Django 5.0.4 on 2024-05-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloging", "0002_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/", verbose_name="изображение"
            ),
        ),
    ]
